config/routes.rb
Rails.application.routes.draw do
  # get "home/index"
  # GET /about
  get "translatep", to: "translatep#index"
  get "sign_up", to: "registration#new"
  post "sign_up", to: "registration#create"

  get "sign_in", to: "sessions#new"
  post "sign_in", to: "sessions#create"
  get "dashboard", to: "sessions#dashboard"


  delete "logout", to: "sessions#destroy"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/*
  get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker
  get "manifest" => "rails/pwa#manifest", as: :pwa_manifest

  # Defines the root path route ("/")
  root to: "main#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/current.rb
class Current < ActiveSupport::CurrentAttributes
  attribute :user
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password
  validates :email, presence: true, format: { with: /\A[^@\s]+@[^@\s]+\z/, message: "must be a valid email address" }
end

app/models/usera.rb
#email:string
#password_digest:string
#is_active:boolean
#
#password:string virtual
#password_confirmation:string virtual


class Usera < ApplicationRecord
  has_secure_password
  validates :email, presence: true, format: { with: /\A[^@\s]+@[^@\s]+\z/, message: "must be a valid email address" }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Only allow modern browsers supporting webp images, web push, badges, import maps, CSS nesting, and CSS :has.
  # allow_browser versions: :modern
  before_action :set_current_user
  # before_action :check_session_expiration

  # private
  def set_current_user
    if session[:user_id]
      Current.user = Usera.find_by(id: session[:user_id])
    end
  end
end

#   def check_session_expiration
#     if session[:user_id].present? && session_expired?
#       session[:user_id] = nil
#       redirect_to root_path, alert: "Your session has expired. Please log in again."
#     end
#   end

#   def session_expired?
#     session[:expires_at].nil? || session[:expires_at] < Time.current
#   end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    session[:user_id] = @usera&.id
    if session[:user_id]
      @usera = Usera.find_by(session[:user_id])
      # @object&.id
      # if @usera.nil?
      # else
      # end
    end
  end
end

app/controllers/main_controller.rb
class MainController < ApplicationController
  def index
      #if session[:user_id]
      #  @usera = Usera.find_by(id: session[:user_id])
      #end
  end
end

app/controllers/registration_controller.rb
class RegistrationController < ApplicationController
  def new
     @usera = Usera.new
  end
  def create
    # render plain: params[:usera]
    @usera = Usera.new(usera_params)
    @usera.is_active ||= false
    if @usera.save
      # session[:user_id] = @usera.id
      redirect_to root_path, notice: "Successfully created account. To access it should be activated"
    else
      render :new
    end
  end

  private

  def usera_params
    params.require(:usera).permit(:email, :password, :password_confirmation, :is_active)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def destroy
    session[:user_id] = nil
    redirect_to root_path, notice: "Logged out"
  end
  def new
  end
  def create
       user = Usera.find_by(email: params[:email], is_active: true)
       if user.present? && user.authenticate(params[:password])
        session[:user_id] = user.id
        # session[:expires_at] = 1.minute.from_now
        # redirect_to root_path, notice: "Logged in Successfully"
        redirect_to dashboard_path
       else
         flash[:alert] = "Invalid email or password"
         render :new
       end
  end
end

app/controllers/translatep_controller.rb
class TranslatepController < ApplicationController
  def translatep
    render layout: "Translatep"
  end
 end
 
# class TranslatepController < ApplicationController
#  def index
#  end
# end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/index.html.erb
<div class="d-flex align-items-center justify-content-center">
    <h1>Home Page</h1>
     <% if @usera %>
        Logged in as: <%= @usera.email %>
     <% end %>
</div>
<%
=begin%>
 <p> This is the Index Page for Alfonso Application</p>
<p>Hellouu, Alfonso 22 24</p> 
<%
=end%>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ApplicationHome</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <% flash.each do |key, value| %>
    <div class="flash <%= key %>"><%= value %></div>
    <% end %>

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>   
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
  </head>
  <body>
    <%= render partial: "shared/navbar" %>
    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>

app/views/layouts/translatep.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Secondary Page</title>
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>   
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
</head>
<body>
  <%= render partial: "shared/navbar" %>
  <%= yield %>
</body>
</html>

app/views/main/index.html.erb
<div class="grid text-center" style="--bs-gap: .25rem 1rem;">
      <div class="g-col-3">
        <i class="bi bi-bootstrap-reboot"></i>
      </div>
      <div class="g-col-4">
      </div>
      <div class="g-col-6">
        <h1 class="s-tit">Welcome to:</h1>
      </div>
      <div class="g-col-0">
      </div>
      <div class="g-col-6">
        <h1 class="s-titdos">Translate4me</h1>
      </div>
</div>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light navbar-small-font">
  <div class="container-fluid">
   <ul class="navbar-nav bg-light ms-auto mb-1 mb-lg-0 navbar-small-font">
      <% if Current.user %>
      <li class="nav-item">
        <a class="nav-link disabled" aria-disabled="true"><%= Current.user.email %></a>
      </li>
      <li class="nav-item">
        <%= button_to "Logout", logout_path, method: :delete, class: "nav-link" %>
      </li>
      <% else %>
      <li class="nav-item">
         <%= link_to "Home", root_path, class: "nav-link" %>
      </li>
      <li class="nav-item">
        <%= link_to "Sign Up", sign_up_path, class: "nav-link" %>
      </li>
      <li class="nav-item">
         <%= link_to "Login", sign_in_path, class: "nav-link" %>
      </li>
      <% end %>
    </ul>
  </div> 
</nav>

app/views/shared/tmp.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light navbar-small-font">
  <div class="container-fluid">
    <ul class="nav justify-content-end">
      <li class="nav-item">
        <%= link_to "Home", root_path, class: "nav-link" %>
      </li>
    </ul>
    <ul class="navbar-nav bg-light ms-auto mb-1 mb-lg-0 navbar-small-font">
      <% if Current.user %>
      <li class="nav-item">
        <a class="nav-link disabled" aria-disabled="true"><%= Current.user.email %></a>
      </li>
      <li class="nav-item">
        <%= button_to "Logout", logout_path, method: :delete, class: "nav-link" %>
      </li>
      <% else %>
      <li class="nav-item">
        <%= link_to "Sign Up", sign_up_path, class: "nav-link" %>
      </li>
      <li class="nav-item">
         <%= link_to "Login", sign_in_path, class: "nav-link" %>
      </li>
      <% end %>
    </ul>
  </div> 
</nav>

app/views/translatep/index.html.erb
<div class="d-flex align-items-center justify-content-center">
    <h1>Translate Page</h1>
</div>
<p> This is the Index Page for Alfonso Application</p>
<p>Hellouu, Alfonso 99999 </p>